# Generated by Django 2.2.1 on 2019-05-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryInfo2',
        ),
    ]
